services:
  - type: staticSite # Ou 'web' si vous servez statiquement depuis un service web
    name: ProjetMariage-FullStack-Front # Le nom de votre service sur Render
    staticPublishPath: build # Ou 'dist' si c'est le nom de votre dossier de build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
